name: blackhole
description: An Open Source Music Player App.

# Prevent accidental publishing to pub.dev.
publish_to: "none"

version: 1.15.0+31

environment:
  sdk: ">=2.13.0 <3.0.0"

dependencies:
  app_links: 2.2.2
  audio_service: ^0.18.5
  audiotagger: ^2.2.1
  # bitsdojo_window: ^0.1.1+1 #For Desktops
  cached_network_image: ^3.2.1
  carousel_slider: ^4.0.0
  cupertino_icons: ^1.0.5
  dart_des: ^1.0.2
  device_info_plus: ^3.2.4
  file_picker: ^4.6.1
  flip_card: ^0.6.0
  flutter:
    sdk: flutter
  flutter_archive: ^4.2.2
  flutter_displaymode: ^0.4.0
  # flutter_downloader: ^1.7.1
  flutter_localizations:
    sdk: flutter
  get_it: ^7.2.0
  hive: ^2.2.2
  hive_flutter: ^1.1.0
  html_unescape: ^2.0.0
  just_audio: ^0.9.24
  just_audio_libwinmedia: ^0.0.4 # For windows and linux
  # logging: ^1.0.1
  marquee: ^2.2.3
  material_design_icons_flutter: 5.0.5955-rc.1
  on_audio_query: ^2.6.1
  package_info_plus: ^1.4.0
  palette_generator: ^0.3.3+1
  path_provider: ^2.0.11
  permission_handler: ^9.2.0
  receive_sharing_intent: ^1.4.5
  salomon_bottom_bar: ^3.3.1
  share_plus: ^4.0.8
  sliding_up_panel: ^2.0.0+1
  supabase: ^0.2.15
  url_launcher: ^6.1.3
  uuid: ^3.0.6
  youtube_explode_dart: 1.10.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  lint: ^1.8.2
  msix: ^3.6.2

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets to the application.
    - assets/

msix_config:
  display_name: BlackHole
  publisher_display_name: Ankit Sangwan
  identity_name: com.shadow.blackhole
  icons_background_color: transparent
  logo_path: assets/ic_launcher.png
  file_extension: .mp3, .m4a
