name: blackhole
description: A Flutter Music Player.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.10.1+17

environment:
  sdk: '>=2.13.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter


  # Audio related
  audiotagger: ^2.2.1
  audio_service: ^0.17.1
  audio_session: ^0.1.5
  just_audio: ^0.9.5
  

  # Productivity
  app_links: ^2.2.0
  cached_network_image: ^3.1.0
  dart_des: ^1.0.0
  # flutter_downloader: ^1.6.1
  flutter_ffmpeg: ^0.4.2
  html_unescape: ^2.0.0
  http: ^0.13.3
  package_info: ^2.0.2
  share_plus: ^2.1.4
  url_launcher: ^6.0.9
  uuid: ^3.0.4
  youtube_explode_dart: ^1.9.10

  
  # UI related
  cupertino_icons: ^1.0.3
  material_design_icons_flutter: ^5.0.5955-rc.1
  material_floating_search_bar: ^0.3.4
  miniplayer:
    git:
      url: https://github.com/Sangwan5688/miniplayer.git
      ref: 9ddb87c650dce69bf04d297543b73fac7de462f2
  salomon_bottom_bar: ^3.1.0

  # Database related
  hive: ^2.0.4
  hive_flutter: ^1.1.0
  supabase: ^0.2.1
  
  # Storage related
  ext_storage:
    git:
      url: git://github.com/GitJournal/ext_storage.git
  file_picker: ^4.0.0
  path_provider: ^2.0.2
  permission_handler: ^8.1.4+2
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  lint: ^1.6.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
